[package]
name = "base24"
version = "0.2.1"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
description = "A simple base24 implementation in Rust"
repository = "https://github.com/sphinxc0re/rust-base24"
license = "MIT"
edition = "2018"

[dev-dependencies]
rand = "0.7.3"
